#requires -Version 7.0

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot = $PSScriptRoot
$sourceRoot = Join-Path $repoRoot 'agents'
$outputRoot = Join-Path $repoRoot '.codebuddy\agents'

$profiles = [ordered]@{
    'implementer' = @{
        PermissionMode = 'acceptEdits'
        Tools = 'Read, Write, Edit, Glob, Grep, Bash'
    }
    'verifier' = @{
        PermissionMode = 'plan'
        Tools = 'Read, Glob, Grep, Bash'
    }
    'standards-reviewer' = @{
        PermissionMode = 'plan'
        Tools = 'Read, Glob, Grep, Bash'
    }
    'spec-reviewer' = @{
        PermissionMode = 'plan'
        Tools = 'Read, Glob, Grep, Bash'
    }
    'reviser' = @{
        PermissionMode = 'acceptEdits'
        Tools = 'Read, Write, Edit, Glob, Grep, Bash'
    }
}

if (-not (Test-Path -LiteralPath $outputRoot)) {
    New-Item -ItemType Directory -Path $outputRoot -Force | Out-Null
}

foreach ($agentName in $profiles.Keys) {
    $sourcePath = Join-Path $sourceRoot "$agentName.md"
    if (-not (Test-Path -LiteralPath $sourcePath)) {
        throw "Отсутствует канонический агент: $sourcePath"
    }

    $raw = Get-Content -LiteralPath $sourcePath -Raw
    $documentMatch = [regex]::Match(
        $raw,
        '\A---\r?\n(?<frontmatter>.*?)\r?\n---\r?\n(?<body>.*)\z',
        [System.Text.RegularExpressions.RegexOptions]::Singleline)
    if (-not $documentMatch.Success) {
        throw "Некорректный frontmatter: $sourcePath"
    }

    $frontmatter = $documentMatch.Groups['frontmatter'].Value
    $descriptionMatch = [regex]::Match($frontmatter, '(?m)^description:\s*(?<value>.+)$')
    if (-not $descriptionMatch.Success) {
        throw "В $sourcePath отсутствует description"
    }

    $description = $descriptionMatch.Groups['value'].Value.Trim().Trim('"').Trim("'")
    $body = $documentMatch.Groups['body'].Value.Trim()
    $profile = $profiles[$agentName]
    $generated = @(
        '---'
        '# Generated by sync-codebuddy-agents.ps1. Do not edit manually.'
        "name: $agentName"
        "description: $description"
        "tools: $($profile.Tools)"
        "permissionMode: $($profile.PermissionMode)"
        '---'
        ''
        $body
    ) -join "`n"

    Set-Content -LiteralPath (Join-Path $outputRoot "$agentName.md") -Value $generated -Encoding utf8NoBOM
}

Get-ChildItem -LiteralPath $outputRoot -Filter '*.md' -File |
    Where-Object { $_.BaseName -notin $profiles.Keys } |
    Remove-Item -Force

Write-Host "Generated $($profiles.Count) CodeBuddy agent profiles."
