#requires -Version 7.0

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$repoRoot = $PSScriptRoot
$sourceRoot = Join-Path $repoRoot 'agents'
$outputRoot = Join-Path $repoRoot '.codex\agents'

$profiles = [ordered]@{
    'implementer' = @{
        Model = 'gpt-5.6-terra'
        ReasoningEffort = 'medium'
        SandboxMode = 'workspace-write'
    }
    'verifier' = @{
        Model = 'gpt-5.6-luna'
        ReasoningEffort = 'low'
        SandboxMode = 'read-only'
    }
    'standards-reviewer' = @{
        Model = 'gpt-5.6-sol'
        ReasoningEffort = 'medium'
        SandboxMode = 'read-only'
    }
    'spec-reviewer' = @{
        Model = 'gpt-5.6-sol'
        ReasoningEffort = 'medium'
        SandboxMode = 'read-only'
    }
    'reviser' = @{
        Model = 'gpt-5.6-terra'
        ReasoningEffort = 'medium'
        SandboxMode = 'workspace-write'
    }
}

function ConvertTo-TomlString {
    param([Parameter(Mandatory)][string]$Value)

    return $Value.Replace('\', '\\').Replace('"', '\"')
}

if (-not (Test-Path -LiteralPath $outputRoot)) {
    New-Item -ItemType Directory -Path $outputRoot -Force | Out-Null
}

foreach ($agentName in $profiles.Keys) {
    $sourcePath = Join-Path $sourceRoot "$agentName.md"
    if (-not (Test-Path -LiteralPath $sourcePath)) {
        throw "Отсутствует канонический агент: $sourcePath"
    }

    $raw = Get-Content -LiteralPath $sourcePath -Raw
    $documentMatch = [regex]::Match(
        $raw,
        '\A---\r?\n(?<frontmatter>.*?)\r?\n---\r?\n(?<body>.*)\z',
        [System.Text.RegularExpressions.RegexOptions]::Singleline)
    if (-not $documentMatch.Success) {
        throw "Некорректный frontmatter: $sourcePath"
    }

    $frontmatter = $documentMatch.Groups['frontmatter'].Value
    $descriptionMatch = [regex]::Match($frontmatter, '(?m)^description:\s*(?<value>.+)$')
    if (-not $descriptionMatch.Success) {
        throw "В $sourcePath отсутствует description"
    }

    $description = $descriptionMatch.Groups['value'].Value.Trim().Trim('"').Trim("'")
    $body = $documentMatch.Groups['body'].Value.Trim()
    if ($body.Contains('"""')) {
        throw "Body $sourcePath содержит TOML multiline delimiter"
    }

    $profile = $profiles[$agentName]
    $generated = @(
        '# Generated by sync-codex-agents.ps1. Do not edit manually.'
        ('name = "{0}"' -f (ConvertTo-TomlString $agentName))
        ('description = "{0}"' -f (ConvertTo-TomlString $description))
        ('model = "{0}"' -f $profile.Model)
        ('model_reasoning_effort = "{0}"' -f $profile.ReasoningEffort)
        ('sandbox_mode = "{0}"' -f $profile.SandboxMode)
        'developer_instructions = """'
        $body
        '"""'
    ) -join "`n"

    $outputPath = Join-Path $outputRoot "$agentName.toml"
    Set-Content -LiteralPath $outputPath -Value $generated -Encoding utf8NoBOM
}

foreach ($staleName in @('reviewer.toml', 'rr-loop.toml')) {
    $stalePath = Join-Path $outputRoot $staleName
    if (Test-Path -LiteralPath $stalePath) {
        Remove-Item -LiteralPath $stalePath -Force
    }
}

Write-Host "Generated $($profiles.Count) Codex agent profiles."
